image: node:6

cache:
    paths:
        - node_modules

build:
    script:
        - yarn
        - npm run build
#    artifacts:
#        paths:
#            - dist/

deploy to test:
    stage: deploy
    only:
        - dev@mgmsic-eig/carto-accidents-verbalisations
    script:
        - sed -i "s|ASSETS_PUBLIC_PATH|/demo/carto-test|g" dist/index.html
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - scp -r dist/* grabenertr@10.237.4.62:/data/www/demo/carto-test
    environment: test
