version: '2'

services:
  cartav-build-preprod:
    build: 
      context: .
      dockerfile: Dockerfile.build-preprod
      args:
        proxy: ${http_proxy}
    image: cartav-build-preprod:latest
    container_name: cartav-build-preprod
    volumes:
      - ./build:/cartav/build
      - ./config:/cartav/config
      - ./index.html:/cartav/index.html
      - ./src:/cartav/src
      - ./static:/cartav/static
      - ./dist:/cartav/dist/
      - ./.eslintrc.js:/cartav/.eslintrc.js
      - ./.eslintignore:/cartav/.eslintignore
      - ./.babelrc:/cartav/.babelrc
