version: '2'

services:
  nginx:
    image: nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-run.template:/etc/nginx/templates/default.conf.template
      - ./dist:/usr/share/nginx/html
    environment:
      - APP_PATH=${APP_PATH}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: always

  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-esnode1
    environment:
      - cluster.name=cartav-cluster
      - bootstrap.memory_lock=true
      - path.repo=/home
      - "ES_JAVA_OPTS=-Xms${ES_MEM} -Xmx${ES_MEM}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./${ES_DATA}:/usr/share/elasticsearch/data


networks:
  default:
    external:
      name: ${APP}
