FROM node:8
ARG proxy
ARG APP_PATH

ENV APP_PATH ${APP_PATH}

WORKDIR /cartav
COPY package.json .

RUN env

# cache package.json and node_modules to speed up builds
RUN npm config `echo $proxy | sed 's/^$/delete proxy/;s/\(\S\S*\)/set proxy \1/'`
RUN npm install


CMD ["npm","run","build-production"]

