version: '2'

services:
  nginx:
    image: nginx
    container_name: cartav-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-dev.template:/etc/nginx/conf.d/default.template
    command: /bin/bash -c '(sed "s|<APP_PATH>|${APP_PATH}|g;" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf) && nginx -g "daemon off;"' 
    ports:
      - "${PORT}:80"
    restart: always


  cartav-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        proxy: ${http_proxy}
        APP_PATH: ${APP_PATH}
    image: cartav-dev:latest
    container_name: cartav-dev
    volumes:
      - ./build:/cartav/build
      - ./config:/cartav/config
      - ./index.html:/cartav/index.html
      - ./src:/cartav/src
      - ./static:/cartav/static
      - ./dist:/cartav/dist/
      - ./.eslintrc.js:/cartav/.eslintrc.js
      - ./.eslintignore:/cartav/.eslintignore
      - ./.babelrc:/cartav/.babelrc
 
  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: cartav-esnode1
    environment:
      - cluster.name=cartav-cluster
      - bootstrap.memory_lock=true
      - path.repo=/home
      - "ES_JAVA_OPTS=-Xms${ES_MEM} -Xmx${ES_MEM}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./${ES_DATA}:/usr/share/elasticsearch/data


