version: '2'

services:
  nginx:
    image: nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-run.template:/etc/nginx/conf.d/default.template
      - ./htpasswd.av.users:/etc/nginx/htpasswd.av.users
      - ./dist:/usr/share/nginx/html
    command: /bin/bash -c '(sed "s|<APP_PATH>|${APP_PATH}|g;" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf) && nginx -g "daemon off;"' 
    environment:
      - APP_PATH:${APP_PATH}
    ports:
      - "${PORT}:80"
    restart: always

  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-esnode1
    environment:
      - cluster.name=cartav-cluster
      - bootstrap.memory_lock=true
      - path.repo=/home
      - "ES_JAVA_OPTS=-Xms${ES_MEM} -Xmx${ES_MEM}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./${ES_DATA}:/usr/share/elasticsearch/data


networks:
  default:
    external:
      name: ${APP}
