version: '2'

services:

  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: cartav-elasticsearch
    environment:
      - cluster.name=cartav-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 6g
    volumes:
      - /data/bases/cartav/node:/usr/share/elasticsearch/data

networks:
  default:
    external:
      name: matchid