version: '2'

services:
  cartav-build:
    build: 
      context: .
      dockerfile: Dockerfile.build
      args:
        proxy: ${http_proxy}
        APP_PATH: ${APP_PATH}
    image: cartav-build:latest
    container_name: cartav-build
    volumes:
      - ./build:/cartav/build
      - ./config:/cartav/config
      - ./index.html:/cartav/index.html
      - ./src:/cartav/src
      - ./static:/cartav/static
      - ./build-dist:/cartav/dist/
      - ./.eslintrc.js:/cartav/.eslintrc.js
      - ./.eslintignore:/cartav/.eslintignore
      - ./.babelrc:/cartav/.babelrc
