version: '2'

services:
  nginx:
    image: nginx
    container_name: cartav-nginx
    # depends_on:
    #   - esnode1
    #   - esnode2
    #   - esnode3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always

  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: cartav-esnode1
    environment:
      - cluster.name=cartav-cluster
      - bootstrap.memory_lock=true
      - path.repo=/home
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - /data/bases/cartav/node:/usr/share/elasticsearch/data
      - /data/bases/cartav/backup/:/home
  # esnode2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
  #   container_name: cartav-esnode2
  #   environment:
  #     - cluster.name=cartav-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
  #     - path.repo=/home
  #     - "discovery.zen.ping.unicast.hosts=esnode1"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 3g
  #   volumes:
  #     - /data/bases/cartav/node2:/usr/share/elasticsearch/data

  # esnode3:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
  #   container_name: cartav-esnode3
  #   environment:
  #     - cluster.name=cartav-cluster
  #     - bootstrap.memory_lock=true
  #     - path.repo=/home
  #     - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
  #     - "discovery.zen.ping.unicast.hosts=esnode1"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 3g
  #   volumes:
  #     - /data/bases/cartav/node3:/usr/share/elasticsearch/data
